// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// For more information about Firebase configuration, visit
// https://firebase.google.com/docs/web/setup
import type {FirebaseOptions} from 'firebase/app';

/**
 * The Firebase configuration object.
 */
export const firebaseConfig: FirebaseOptions = JSON.parse(
  process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{"projectId":"test-project"}'
);
