// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// For more information about Firebase configuration, visit
// https://firebase.google.com/docs/web/setup
import type {FirebaseOptions} from 'firebase/app';

/**
 * The Firebase configuration object.
 */
export const firebaseConfig: FirebaseOptions = {
  apiKey: 'API_KEY',
  authDomain: 'PROJECT_ID.firebaseapp.com',
  projectId: 'PROJECT_ID',
  storageBucket: 'PROJECT_ID.appspot.com',
  messagingSenderId: 'SENDER_ID',
  appId: 'APP_ID',
};
